
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.104:3306/security?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  redis:
    database: 1
    host: 192.168.0.104
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  #    把返回到前端的时间变成时间戳
  jackson:
    serialization:
      write-dates-as-timestamps: true
  session:
    store-type: none
security:
    basic:
      enabled: false
server:
  port: 80

#wzb:
#  security:
#        code:
#          image:
#            length: 6
#            width: 100
# 什么样的验证码需要验证, 下面的url
#            url: /user/*
#    browser:
#      loginPage: /demo-signIn.html
#      loginResponseType: REDIRECT

wzb:
  security:
      social:
        filterProcessesUrl: /qqLogin
        qq:
          app-id: 100550231
          app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
          providerId: callback.do
