spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.104:3306/security?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
#    把返回到前端的时间变成时间戳
  jackson:
    serialization:
      write-dates-as-timestamps: true
  session:
    store-type: none
security:
    basic:
     en
server:
  port: 8060

wzb:
  security:
    browserProperties:
#      loginPage: /demo-signIn.html
      loginResponseType: REDIRECT