
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.10:3306/security?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Abc!@123
  redis:
    database: 1
    host: 192.168.0.10
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  #    把返回到前端的时间变成时间戳
  jackson:
    serialization:
      write-dates-as-timestamps: true
  session:
    store-type: none
security:
    basic:
      enabled: false
#      注意QQ登录默认是80端口
server:
  port: 80

wzb:
  security:
      code:
        image:
          length: 6
          width: 100
# 什么样的验证码需要验证, 下面的url
          url: /user/*
      browser:
        loginPage: /demo-signIn.html
        loginResponseType: REDIRECT
        signUpUrl: /demo-signUp.html
      social:
        filterProcessesUrl: /qqLogin
        qq:
          app-id: 101860144
          app-secret: 8f92b83413f0c899bc284d2b27fdb82a
          providerId: callback.do
